# roles/zookeeper/tasks/main.yml
---
- import_tasks: apply.yml
  tags:
    - apply

- import_tasks: configure.yml
  tags:
    - configure

- import_tasks: initialize.yml
  tags:
    - initialize

- import_tasks: check.yml
  tags:
    - check

